SELECT * FROM cognidemo1.title;

/*using cognidemo1 db*/
use cognidemo1;

/* 1st question answer */
SELECT FIRST_NAME AS WORKER_NAME FROM WORKER;

/* 2nd question answer */
SELECT UPPER(FIRST_NAME) FROM WORKER;

/* 3rd question answer */
SELECT distinct(DEPARTMENT) FROM WORKER;

/* 4th question answer */
SELECT substring(FIRST_NAME,1,3) FROM WORKER;

/* 5TH question answer */
SELECT POSITION("A" IN "AMITABH") AS POSITION;

/* 6th question answer */
SELECT RTRIM(FIRST_NAME) FROM WORKER;

/* 7th question answer */
SELECT LTRIM(DEPARTMENT) FROM WORKER;

/* 8th question answer */
SELECT DISTINCT(LENGTH(DEPARTMENT)) FROM WORKER;

/* 9th question answer */
SELECT REPLACE(FIRST_NAME,'a','A') FROM WORKER;

/* 10th question answer */
SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS COMPLETE_NAME FROM WORKER;

/* 11th question answer */
SELECT * FROM WORKER ORDER BY FIRST_NAME;

/* 12th question answer */
SELECT *FROM (SELECT * FROM WORKER ORDER BY FIRST_NAME)FNAME ORDER BY FNAME.DEPARTMENT DESC;

/* 13th question answer */
SELECT * FROM WORKER WHERE FIRST_NAME="VIPUL" OR FIRST_NAME="SATISH";

/* 14th question answer */
SELECT * FROM WORKER WHERE FIRST_NAME !="Vipul" AND FIRST_NAME !="Satish";

/* 15th question answer */
SELECT * FROM WORKER WHERE DEPARTMENT="Admin";

/* 16th question answer */
SELECT * FROM WORKER WHERE FIRST_NAME LIKE "a%";

/* 17th question answer */
SELECT * FROM WORKER WHERE FIRST_NAME LIKE "%a";

/* 18th question answer */
SELECT * FROM WORKER WHERE FIRST_NAME LIKE "%h" and length(FIRST_NAME)=6;

/* 19th question answer */
SELECT * FROM WORKER WHERE SALARY >=100000 AND SALARY<=500000;

SELECT * FROM WORKER;
/* 20th question answer */
SELECT * FROM WORKER WHERE JOINING_DATE LIKE "2014-02%";

/* 21st question answer */
SELECT COUNT(DEPARTMENT)FROM WORKER WHERE DEPARTMENT="Admin"; 

/* 22nd question answer */
SELECT * FROM WORKER WHERE SALARY>=500000 OR SALARY<=100000;

/* 23rd question answer */
SELECT COUNT(WORKER_ID),DEPARTMENT FROM WORKER GROUP BY DEPARTMENT ORDER BY DEPARTMENT DESC;

/* 24th question answer */
SELECT * FROM WORKER W,TITLE T WHERE W.WORKER_ID=T.WORKER_REF_ID AND T.WORKER_TITLE="MANAGER";

/* 25th question answer */
SELECT * FROM TITLE T,(SELECT COUNT(WORKER_REF_ID),WORKER_TITLE FROM TITLE GROUP BY WORKER_TITLE HAVING COUNT(WORKER_REF_ID)=1) W WHERE T.WORKER_TITLE=W.WORKER_TITLE;

/* 26th question answer */
SELECT * FROM WORKER WHERE MOD(WORKER_ID,2)<>0;

/* 27th question answer */
SELECT * FROM WORKER WHERE MOD(WORKER_ID,2)=0;

/* 28th question answer */
CREATE TABLE WORKER_CLONE SELECT * FROM WORKER;
SELECT * FROM WORKER_CLONE;

/* 29th question answer */
SELECT * FROM WORKER JOIN BONUS ON WORKER.WORKER_ID=BONUS.WORKER_REF_ID;

/* 30th question answer */
SELECT * FROM WORKER WHERE WORKER_ID NOT IN(SELECT WORKER_REF_ID FROM BONUS);



